### ISSUE TITLE
why switch to python wrapper of GCVSPL, instead of the old Julia wrapper?

### ISSUE THREAD

**Issue by babaq** [charlesll/Spectra.jl#14]
Hi,

I found `Spectra.jl` when searching for a smooth spline package with GCV/DOF. The google search result leads me to the old version of Spectra which warp the GCVSPL Fortran library directly. However, the new version favors PyCall to the python wrapper which would seem decrease performance.

Actually, I am more interested whether the authors would like to separate the old Julia wrapper to a separate package. Right now, no Julia smooth spline packages exist with GCV/DOF, which I need in my package that requires high performance.

Best,

Alex

**Comment by charlesll** [comment]
Hi,

The switch to the Python wrapper was because I ran into some trouble at some point for maintaining the Julia wrapper, particularly upon the rapid switch between Julia 0.5, 0/6 and 1.0... We started developing one stable wrapper in Python, so as my time is limited, I preferred focusing on developing the Python version and use PyCall to provide access in Julia.

(Another point : I got sick of Windows struggling to install Spectra because of the requirement of a FORTRAN compiler.)

Now that Julia is in a more "stable" version, yes, we could easily provide access to a Julia wrapper. I guess we could take the old code of Spectra as a starting point, and work on a wrapper.

**Comment by charlesll** [comment]
Here I created the skeleton of a package for the Julia library : https://github.com/charlesll/gcvspl

Feel free to modify and add your name to contributors :)

**Comment by charlesll** [comment]
@babaq I setup a working wrapper of the GCVSPL library, see at https://github.com/charlesll/gcvspl

Registry of a version 0.1 has been requested, so it should be soon available. You can already install locally if you grab the github repo, there is a working example in the example folder, and the documentation is actually that of the FORTRAN code.

Please don't hesitate to let me know if it works and what needs to be improved, etc. 

Best,
Charles
